name: Deploy to GCP VM 2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pm2
        run: npm install -g pm2

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 34.69.159.152
          username: gcp
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd /home/runner/company-profile
            pwd 
            ls -la
            git pull origin master
            sudo docker compose down
            sudo docker compose up
      


