name: Deploy to GCP VM 2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: /

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pm2
        run: npm install -g pm2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add Host Key
        run: ssh-keyscan -H 34.69.159.152 >> ~/.ssh/known_hosts

      - name: SSH into GCP VM
        run: ssh -i ${{ secrets.SSH_PRIVATE_KEY }} gcp@34.69.159.152 && cd /home/gcp/
      
      - name: Build Nextjs
        run:  git pull origin master && npm install && sudo npm run build && pm2 restart npm 

