name: CI/CD with Next.js and GCP VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build Next.js App
        run: npm run build

      - name: Deploy to GCP VM
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
          VM_IP: '34.69.159.152'
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          gcloud auth activate-service-account --key-file=<(echo "$SERVICE_ACCOUNT_KEY")
          scp -i <(echo "$SSH_PRIVATE_KEY") -r ./* gcp@$VM_IP:/path/to/your/nextjs/app
          ssh -i <(echo "$SSH_PRIVATE_KEY") gcp@$VM_IP 'bash -s' < ./deploy.sh
