name: Deploy to GCP VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pm2
        run: npm install -g pm2

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa

      - name: Add GCP VM Host Key to Known Hosts
        run: ssh-keyscan -H 34.69.159.152 >> ~/.ssh/known_hosts

      - name: SSH into GCP VM
        run: ssh -i ~/.ssh/id_rsa gcp@34.69.159.152 && cd company-profile && git pull origin master && npm install && sudo npm run build && pm2 restart npm

