name: Deploy to GCP VM 2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: /

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install pm2
        run: npm install -g pm2

      - name: Checkout Repository
        uses: actions/checkout@v2

      - uses: google-github-actions/ssh-compute@main
        with:
          instance_name: fr-1
          zone: us-central1-c  # Replace with your zone
          private_key: ${{ secrets.SSH_PRIVATE_KEY }}